version: '3'
services:
  pocketbase:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - ./pb_data:/root/pocketbase/pb_data
      - ./pb_hooks:/root/pb_hooks